version: '3.8'

services:
  db:
    image: bitnami/mysql:latest
    environment:
      MYSQL_DATABASE: product_list_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: root_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app-network

  backend:
    build: ./product_list
    ports:
      - "3333:3333"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/product_list_db
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: password
    networks:
      - app-network
    entrypoint: ["sh", "-c", "/usr/bin/wait-for-it db:3306 -- sleep 50 && java -cp app:app/lib/* com.projeto.product_list.ProductListApplication"]

  frontend:
    build: ./web/app-produto
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - app-network
    entrypoint: ["sh", "-c", "/usr/bin/wait-for-it backend:3333 -- npm run start"]

volumes:
  mysql_data:

networks:
  app-network:
    driver: bridge
